package jetbrains.mps.baseLanguage.tailRecursion.generator.util;

/*Generated by MPS */

import jetbrains.mps.generator.template.TemplateQueryContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.closures.runtime.YieldingIterator;
import jetbrains.mps.internal.collections.runtime.StopIteratingException;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;
import jetbrains.mps.lang.typesystem.runtime.HUtil;

public class GenHelper {
  public GenHelper() {
  }

  public static void checkPathForIncorrectNodes(TemplateQueryContext genContext, final SNode lastNode, SNode methodCall) {
    if (SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement")) {
      if (SLinkOperations.getTarget(SNodeOperations.cast(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement"), "expression", true) != methodCall) {
        genContext.showErrorMessage(methodCall, "The method call is not in a tail position");
      }
    } else if (SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement")) {
      if (SLinkOperations.getTarget(SNodeOperations.cast(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"), "expression", true) != methodCall) {
        genContext.showErrorMessage(methodCall, "The method call is not in a tail position");
      }
    } else {
      Iterable<SNode> predecesors = ListSequence.fromList(SNodeOperations.getAncestors(methodCall, null, false)).translate(new ITranslator2<SNode, SNode>() {
        public Iterable<SNode> translate(final SNode it) {
          return new Iterable<SNode>() {
            public Iterator<SNode> iterator() {
              return new YieldingIterator<SNode>() {
                private int __CP__ = 0;

                protected boolean moveToNext() {
__loop__:
                  do {
__switch__:
                    switch (this.__CP__) {
                      case -1:
                        assert false : "Internal error";
                        return false;
                      case 4:
                        if (it == lastNode) {
                          this.__CP__ = 5;
                          break;
                        }
                        this.__CP__ = 6;
                        break;
                      case 3:
                        if (false) {
                          this.__CP__ = 2;
                          break;
                        }
                        this.__CP__ = 1;
                        break;
                      case 6:
                        this.__CP__ = 3;
                        this.yield(it);
                        return true;
                      case 0:
                        this.__CP__ = 2;
                        break;
                      case 2:
                        this.__CP__ = 4;
                        break;
                      case 5:
                        throw new StopIteratingException();
                      default:
                        break __loop__;
                    }
                  } while (true);
                  return false;
                }
              };
            }
          };
        }
      });
      if (Sequence.fromIterable(predecesors).any(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TryCatchStatement") || SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TryStatement") || SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.AbstractLoopStatement");
        }
      })) {
        genContext.showErrorMessage(methodCall, "The method call is not in a tail position");
      }
      checkLastNodeBeingOfCorrectKind(genContext, SNodeOperations.getParent(methodCall));
    }
  }

  public static boolean checkMethodCallInvokesCorrectMethod(SNode method, TemplateQueryContext genContext, SNode methodCall) {
    if (SLinkOperations.getTarget(methodCall, "baseMethodDeclaration", false) != method) {
      genContext.showErrorMessage(methodCall, "The method call is not in a tail position");
      return true;
    }
    return false;
  }

  public static boolean checkLastNodeBeingOfCorrectKind(TemplateQueryContext genContext, SNode lastNode) {
    if (!(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement")) && !(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement")) && !(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.IfStatement"))) {
      genContext.showErrorMessage(lastNode, "The method call is not in a tail position");
      return true;
    }
    return false;
  }

  public static void handleParameter(SNode originalFunctionDefinition, SNode containingStatementList, SNode parameterCopyBlock, final SNode param, SNode currentInvocationParameter, TemplateQueryContext genContext) {

    SNode varDeclaration = new GenHelper.QuotationClass_bzcigv_a0a1a3().createNode(SNodeOperations.copyNode(SLinkOperations.getTarget(param, "type", true)), genContext.createUniqueName("localParam", null), param);
    ListSequence.fromList(SLinkOperations.getTargets(parameterCopyBlock, "statement", true)).addElement(varDeclaration);

    final SNode varRef = new GenHelper.QuotationClass_bzcigv_a0a4a3().createNode(SLinkOperations.getTarget(varDeclaration, "localVariableDeclaration", true));

    SNode assignment = new GenHelper.QuotationClass_bzcigv_a0a6a3().createNode(varRef, currentInvocationParameter);
    ListSequence.fromList(SLinkOperations.getTargets(containingStatementList, "statement", true)).addElement(new GenHelper.QuotationClass_bzcigv_a0a0h0d().createNode(assignment));

    ListSequence.fromList(SNodeOperations.getDescendants(originalFunctionDefinition, "jetbrains.mps.baseLanguage.structure.ParameterReference", false, new String[]{})).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, "variableDeclaration", false) == param;
      }
    }).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        SNodeOperations.replaceWithAnother(it, SNodeOperations.copyNode(varRef));
      }
    });
  }

  public static void removeTailStatement(SNode functionInvocation) {
    SNode returnStatement = SNodeOperations.getAncestor(functionInvocation, "jetbrains.mps.baseLanguage.structure.ReturnStatement", false, false);
    if (returnStatement == null) {
      SNode expressionStatement = SNodeOperations.getAncestor(functionInvocation, "jetbrains.mps.baseLanguage.structure.ExpressionStatement", false, false);
      SNodeOperations.deleteNode(expressionStatement);
    } else {
      SNodeOperations.deleteNode(returnStatement);
    }
  }

  public static SNode wrapInLoop(SNode functionBody, SNode parameterCopyBlock) {
    SNode body = new GenHelper.QuotationClass_bzcigv_a0a0a5().createNode(functionBody);
    final SNode loopNode = ListSequence.fromList(SLinkOperations.getTargets(body, "statement", true)).first();
    ListSequence.fromList(SLinkOperations.getTargets(parameterCopyBlock, "statement", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        SNodeOperations.insertPrevSiblingChild(loopNode, SNodeOperations.detachNode(it));
      }
    });
    return body;
  }

  public static class QuotationClass_bzcigv_a0a1a3 {
    public QuotationClass_bzcigv_a0a1a3() {
    }

    public SNode createNode(Object parameter_9, Object parameter_10, Object parameter_11) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      SNode quotedNode_2 = null;
      SNode quotedNode_3 = null;
      SNode quotedNode_4 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_5 = quotedNode_1;
        {
          quotedNode_2 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration", null, GlobalScope.getInstance(), false);
          SNode quotedNode1_6 = quotedNode_2;
          quotedNode1_6.setProperty("name", (String) parameter_10);
          {
            quotedNode_3 = (SNode) parameter_9;
            SNode quotedNode1_7;
            if (_parameterValues_129834374.contains(quotedNode_3)) {
              quotedNode1_7 = HUtil.copyIfNecessary(quotedNode_3);
            } else {
              _parameterValues_129834374.add(quotedNode_3);
              quotedNode1_7 = quotedNode_3;
            }
            if (quotedNode1_7 != null) {
              quotedNode_2.addChild("type", HUtil.copyIfNecessary(quotedNode1_7));
            }
          }
          {
            quotedNode_4 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ParameterReference", null, GlobalScope.getInstance(), false);
            SNode quotedNode1_8 = quotedNode_4;
            quotedNode1_8.setReferent("variableDeclaration", (SNode) parameter_11);
            quotedNode_2.addChild("initializer", quotedNode1_8);
          }
          quotedNode_1.addChild("localVariableDeclaration", quotedNode1_6);
        }
        result = quotedNode1_5;
      }
      return result;
    }
  }

  public static class QuotationClass_bzcigv_a0a4a3 {
    public QuotationClass_bzcigv_a0a4a3() {
    }

    public SNode createNode(Object parameter_3) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.LocalVariableReference", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        quotedNode1_2.setReferent("variableDeclaration", (SNode) parameter_3);
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_bzcigv_a0a6a3 {
    public QuotationClass_bzcigv_a0a6a3() {
    }

    public SNode createNode(Object parameter_7, Object parameter_8) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      SNode quotedNode_2 = null;
      SNode quotedNode_3 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.AssignmentExpression", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_4 = quotedNode_1;
        {
          quotedNode_2 = (SNode) parameter_7;
          SNode quotedNode1_5;
          if (_parameterValues_129834374.contains(quotedNode_2)) {
            quotedNode1_5 = HUtil.copyIfNecessary(quotedNode_2);
          } else {
            _parameterValues_129834374.add(quotedNode_2);
            quotedNode1_5 = quotedNode_2;
          }
          if (quotedNode1_5 != null) {
            quotedNode_1.addChild("lValue", HUtil.copyIfNecessary(quotedNode1_5));
          }
        }
        {
          quotedNode_3 = (SNode) parameter_8;
          SNode quotedNode1_6;
          if (_parameterValues_129834374.contains(quotedNode_3)) {
            quotedNode1_6 = HUtil.copyIfNecessary(quotedNode_3);
          } else {
            _parameterValues_129834374.add(quotedNode_3);
            quotedNode1_6 = quotedNode_3;
          }
          if (quotedNode1_6 != null) {
            quotedNode_1.addChild("rValue", HUtil.copyIfNecessary(quotedNode1_6));
          }
        }
        result = quotedNode1_4;
      }
      return result;
    }
  }

  public static class QuotationClass_bzcigv_a0a0h0d {
    public QuotationClass_bzcigv_a0a0h0d() {
    }

    public SNode createNode(Object parameter_5) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      SNode quotedNode_2 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ExpressionStatement", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_3 = quotedNode_1;
        {
          quotedNode_2 = (SNode) parameter_5;
          SNode quotedNode1_4;
          if (_parameterValues_129834374.contains(quotedNode_2)) {
            quotedNode1_4 = HUtil.copyIfNecessary(quotedNode_2);
          } else {
            _parameterValues_129834374.add(quotedNode_2);
            quotedNode1_4 = quotedNode_2;
          }
          if (quotedNode1_4 != null) {
            quotedNode_1.addChild("expression", HUtil.copyIfNecessary(quotedNode1_4));
          }
        }
        result = quotedNode1_3;
      }
      return result;
    }
  }

  public static class QuotationClass_bzcigv_a0a0a5 {
    public QuotationClass_bzcigv_a0a0a5() {
    }

    public SNode createNode(Object parameter_9) {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      SNode quotedNode_2 = null;
      SNode quotedNode_3 = null;
      SNode quotedNode_4 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StatementList", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_5 = quotedNode_1;
        {
          quotedNode_2 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.WhileStatement", null, GlobalScope.getInstance(), false);
          SNode quotedNode1_6 = quotedNode_2;
          {
            quotedNode_3 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.BooleanConstant", null, GlobalScope.getInstance(), false);
            SNode quotedNode1_7 = quotedNode_3;
            quotedNode1_7.setProperty("value", "true");
            quotedNode_2.addChild("condition", quotedNode1_7);
          }
          {
            quotedNode_4 = (SNode) parameter_9;
            SNode quotedNode1_8;
            if (_parameterValues_129834374.contains(quotedNode_4)) {
              quotedNode1_8 = HUtil.copyIfNecessary(quotedNode_4);
            } else {
              _parameterValues_129834374.add(quotedNode_4);
              quotedNode1_8 = quotedNode_4;
            }
            if (quotedNode1_8 != null) {
              quotedNode_2.addChild("body", HUtil.copyIfNecessary(quotedNode1_8));
            }
          }
          quotedNode_1.addChild("statement", quotedNode1_6);
        }
        result = quotedNode1_5;
      }
      return result;
    }
  }
}
