package jetbrains.mps.baseLanguage.tailRecursion.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.dependencies.CheckingMethod;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.closures.runtime.YieldingIterator;
import jetbrains.mps.internal.collections.runtime.StopIteratingException;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;

public class CheckingUtil {
  public CheckingUtil() {
  }

  @CheckingMethod
  public static void checkForVoidReturnType(final TypeCheckingContext typeCheckingContext, SNode returnType, SNode functionDeclaration) {
    if (SNodeOperations.isInstanceOf(returnType, "jetbrains.mps.baseLanguage.structure.VoidType")) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(functionDeclaration, "Tail recursive methods and closures must not return void", "r:293c28b4-50b9-42c3-936c-5778a017e4f1(jetbrains.mps.baseLanguage.tailRecursion.typesystem)", "6963853100979796647", null, errorTarget);
      }
    }
  }

  @CheckingMethod
  public static void checkCorrectKindOfLastNode(final TypeCheckingContext typeCheckingContext, SNode lastNode) {
    if (!(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement")) && !(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement")) && !(SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.IfStatement"))) {
      {
        MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(lastNode, "The recursive invocation doesn't seem to be in the tail position", "r:293c28b4-50b9-42c3-936c-5778a017e4f1(jetbrains.mps.baseLanguage.tailRecursion.typesystem)", "6963853100979796618", null, errorTarget);
      }
    }
  }

  @CheckingMethod
  public static void checkHierarchy(final TypeCheckingContext typeCheckingContext, final SNode lastNode, SNode functionCall) {
    if (SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement")) {
      if (SLinkOperations.getTarget(SNodeOperations.cast(lastNode, "jetbrains.mps.baseLanguage.structure.ReturnStatement"), "expression", true) != functionCall) {
        {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(functionCall, "The recursive invocation doesn't seem to be in the tail position", "r:293c28b4-50b9-42c3-936c-5778a017e4f1(jetbrains.mps.baseLanguage.tailRecursion.typesystem)", "3220419832563448025", null, errorTarget);
        }
      }
    } else if (SNodeOperations.isInstanceOf(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement")) {
      if (SLinkOperations.getTarget(SNodeOperations.cast(lastNode, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"), "expression", true) != functionCall) {
        {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(functionCall, "The recursive invocation doesn't seem to be in the tail position", "r:293c28b4-50b9-42c3-936c-5778a017e4f1(jetbrains.mps.baseLanguage.tailRecursion.typesystem)", "3220419832563448046", null, errorTarget);
        }
      }
    } else {
      Iterable<SNode> predecesors = ListSequence.fromList(SNodeOperations.getAncestors(functionCall, null, false)).translate(new ITranslator2<SNode, SNode>() {
        public Iterable<SNode> translate(final SNode it) {
          return new Iterable<SNode>() {
            public Iterator<SNode> iterator() {
              return new YieldingIterator<SNode>() {
                private int __CP__ = 0;

                protected boolean moveToNext() {
__loop__:
                  do {
__switch__:
                    switch (this.__CP__) {
                      case -1:
                        assert false : "Internal error";
                        return false;
                      case 4:
                        if (it == lastNode) {
                          this.__CP__ = 5;
                          break;
                        }
                        this.__CP__ = 6;
                        break;
                      case 3:
                        if (false) {
                          this.__CP__ = 2;
                          break;
                        }
                        this.__CP__ = 1;
                        break;
                      case 6:
                        this.__CP__ = 3;
                        this.yield(it);
                        return true;
                      case 0:
                        this.__CP__ = 2;
                        break;
                      case 2:
                        this.__CP__ = 4;
                        break;
                      case 5:
                        throw new StopIteratingException();
                      default:
                        break __loop__;
                    }
                  } while (true);
                  return false;
                }
              };
            }
          };
        }
      });
      if (Sequence.fromIterable(predecesors).any(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TryCatchStatement") || SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TryStatement") || SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.AbstractLoopStatement");
        }
      })) {
        {
          MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(functionCall, "The recursive invocation doesn't seem to be in the tail position", "r:293c28b4-50b9-42c3-936c-5778a017e4f1(jetbrains.mps.baseLanguage.tailRecursion.typesystem)", "3220419832563448080", null, errorTarget);
        }
      }
      checkCorrectKindOfLastNode(typeCheckingContext, SNodeOperations.getParent(functionCall));
    }
  }
}
