package jetbrains.mps.baseLanguage.tailRecursion.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("f142cd5e-ea1d-466a-86a8-52891b6256a4(jetbrains.mps.baseLanguage.tailRecursion)"), PersistenceFacade.getInstance().createModelReference("r:6df770e3-0000-4824-9d7d-6d58a2073987(jetbrains.mps.baseLanguage.tailRecursion.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureTailRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodTailRecursive_Intention());
  }
}
