package jetbrains.mps.baseLanguage.tailRecursion.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureTailRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodRecursive_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodTailRecursive_Intention());
  }
}
