package jetbrains.mps.baseLanguage.memoize.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("9f9722b2-7c97-43c8-9771-bea4630e2676(jetbrains.mps.baseLanguage.memoize)"), PersistenceFacade.getInstance().createModelReference("r:73d9b7c1-7a0a-4715-9de3-9f81c22388bf(jetbrains.mps.baseLanguage.memoize.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureMemoized_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeClosureNotMemoized_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodMemoized_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new MakeMethodNotMemoized_Intention());
  }
}
