package jetbrains.mps.baseLanguage.memoize.util.caches;

/*Generated by MPS */

import java.util.LinkedHashMap;

public final class NullProtectionStorage extends LinkedHashMap<Object, Object> {
  public NullProtectionStorage() {
  }
  public void touch(final Object key, final Object value) {
  }
}
