package jetbrains.mps.baseLanguage.tailRecursion.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class TailRecursion_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.tailRecursion.structure.TailRecursion";
  }

}
