package jetbrains.mps.baseLanguage.memoize.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class MemoizeAnnotation_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public MemoizeAnnotation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.memoize.structure.MemoizeAnnotation";
  }
}
