package jetbrains.mps.baseLanguage.memoize.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class MemoizeAnnotation_Behavior {
}
