package jetbrains.mps.baseLanguage.memoize.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;

public class MemoizeAnnotation_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public MemoizeAnnotation_BehaviorDescriptor() {
  }

  public List<SNode> virtual_getAttributed_3044950653914717013(SConcept thisConcept) {
    return MemoizeAnnotation_Behavior.virtual_getAttributed_3044950653914717013(thisConcept);
  }

  public String virtual_getRole_1262430001741497900(SConcept thisConcept) {
    return MemoizeAnnotation_Behavior.virtual_getRole_1262430001741497900(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.memoize.structure.MemoizeAnnotation";
  }
}
