package jetbrains.mps.baseLanguage.memoize.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class MemoizeAnnotation_Behavior {
  public static void init(SNode thisNode) {
  }
}
