package jetbrains.mps.baseLanguage.memoize.sandbox.test;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;

public class CornerCass_Test extends TestCase {
  public void test_methods() throws Exception {
    CornerCaseSpecialist.noArgVoidFunction();
    CornerCaseSpecialist.noArgVoidFunction();

    Assert.assertEquals(0, CornerCaseSpecialist.callCounter);
    CornerCaseSpecialist.noArgFunction();
    Assert.assertEquals(1, CornerCaseSpecialist.callCounter);
    CornerCaseSpecialist.noArgFunction();
    Assert.assertEquals(1, CornerCaseSpecialist.callCounter);

    CornerCaseSpecialist.voidFunction(1);
    CornerCaseSpecialist.voidFunction(1);
  }
  public void test_closures() throws Exception {
    CornerCaseSpecialist specialist = new CornerCaseSpecialist();
    specialist.noArgVoidClosure.invoke();
    specialist.noArgVoidClosure.invoke();

    Assert.assertEquals(0, specialist.counter);
    specialist.noArgClosure.invoke();
    Assert.assertEquals(1, specialist.counter);
    specialist.noArgClosure.invoke();
    Assert.assertEquals(1, specialist.counter);

    specialist.noArgClosure.invoke();
    specialist.noArgClosure.invoke();
  }
  public CornerCass_Test() {
  }
}
