package jetbrains.mps.baseLanguage.memoize.sandbox.test;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.Assert;

public class CornerCass_Test {
  @Test
  public void test_methods() throws Exception {
    CornerCaseSpecialist.noArgVoidFunction();
    CornerCaseSpecialist.noArgVoidFunction();

    Assert.assertEquals(Integer.valueOf(0), Integer.valueOf(CornerCaseSpecialist.callCounter));
    CornerCaseSpecialist.noArgFunction();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(CornerCaseSpecialist.callCounter));
    CornerCaseSpecialist.noArgFunction();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(CornerCaseSpecialist.callCounter));

    CornerCaseSpecialist.voidFunction(1);
    CornerCaseSpecialist.voidFunction(1);
  }
  @Test
  public void test_closures() throws Exception {
    CornerCaseSpecialist specialist = new CornerCaseSpecialist();
    specialist.noArgVoidClosure.invoke();
    specialist.noArgVoidClosure.invoke();

    Assert.assertEquals(Integer.valueOf(0), Integer.valueOf(specialist.counter));
    specialist.noArgClosure.invoke();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(specialist.counter));
    specialist.noArgClosure.invoke();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(specialist.counter));

    specialist.noArgClosure.invoke();
    specialist.noArgClosure.invoke();
  }
}
